version: "3.9"

services:
  database:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: store_management
      POSTGRES_USER: store_user
      POSTGRES_PASSWORD: store_password
      POSTGRES_ROOT_PASSWORD: rootpass
      POSTGRES_PORT: 5432
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"