spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store_management
    username: ${DB_USERNAME:store_user}
    password: ${DB_PASSWORD:store_password}
    driver-class-name: org.postgresql.Driver